apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mathcruncher
  namespace: monitoring           # важно! именно monitoring, где работает Prometheus
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: mathcruncher           # должны совпадать с labels у Service
  namespaceSelector:
    matchNames:
      - mathcruncher
  endpoints:
    - port: http                  # это имя порта в Service (если нет, добавь ниже targetPort: 8080)
      path: /metrics
      interval: 10s
