
deployment: mathcruncher
namespace: mathcruncher
prometheus_url: http://monitoring-kube-prometheus-prometheus.monitoring:9090
interval: 5
scaling:
  target_rps_per_pod: 100
  hysteresis: 1
  max_replicas: 10
