version: '3.8'

services:
  load-balancer:
    build: ./load-balancer
    ports:
      - "8080:8080"
      - "9090:9090" # metrics
    environment:
      - JAEGER_ENDPOINT=http://jaeger:4318
    depends_on:
      - jaeger
      - backend1
      - backend2
    networks:
      - monitoring-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - monitoring-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    depends_on:
      - prometheus
    networks:
      - monitoring-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # UI
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - monitoring-network

  backend1:
    image: hashicorp/http-echo
    command: ["-text", "Backend 1", "-listen", ":8080"]
    ports:
      - "8081:8080"
    networks:
      - monitoring-network

  backend2:
    image: hashicorp/http-echo
    command: ["-text", "Backend 2", "-listen", ":8080"]
    ports:
      - "8082:8080"
    networks:
      - monitoring-network

volumes:
  grafana-data:

networks:
  monitoring-network:
    driver: bridge