---
apiVersion: v1
kind: Service
metadata:
  name: mathcruncher
  namespace: mathcruncher
  labels:
    app: mathcruncher
spec:
  selector:
    app: mathcruncher
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mathcruncher
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: mathcruncher
  namespaceSelector:
    matchNames:
      - mathcruncher
  endpoints:
    - port: http
      path: /metrics
      interval: 10s
