apiVersion: v1
kind: ConfigMap
metadata:
  name: dashboard-config
  namespace: mathcruncher
data:
  PROMETHEUS_URL: "http://monitoring-kube-prometheus-prometheus.monitoring:9090"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscaler-dashboard
  namespace: mathcruncher
spec:
  replicas: 1
  selector:
    matchLabels: {app: autoscaler-dashboard}
  template:
    metadata:
      labels: {app: autoscaler-dashboard}
    spec:
      # serviceAccountName: autoscaler      # ← НЕ нужно, убрать/закомментировать
      containers:
        - name: dashboard
          image: mathcruncher/autoscaler-dashboard:dev   # ваш образ
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: dashboard-config
          ports:
            - containerPort: 8501
          resources:
            requests: {cpu: "100m", memory: "128Mi"}
            limits:   {cpu: "500m", memory: "256Mi"}
