apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mathcruncher
  namespace: mathcruncher
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mathcruncher
  minReplicas: 1           # ← старт с 1 реплики
  maxReplicas: 10         # ← запас под пик
  behavior:                # ← ускоряем scale-up
    scaleUp:
      policies:
        - type: Pods
          value: 5           # +до 5 за шаг
          periodSeconds: 15
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
