apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: template-api
  template:
    metadata:
      labels:
        app: template-api
    spec:
      containers:
        - name: template-api
          image: template-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: template-api
spec:
  clusterIP: None  # <--- Это делает его headless
  selector:
    app: template-api
  ports:
    - port: 80
      targetPort: 8080