scaling:
  min_nodes: 2
  max_nodes: 10
  cpu_threshold: 80
  mem_threshold: 90
  step_size: 2      # Макс. изменение узлов за шаг

metrics:
  - name: cpu_usage
    query: '100 - (avg by (instance)(rate(node_cpu_seconds_total{mode="idle"}[1m])) * 100'
  - name: memory_usage
    query: '(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100'

forecasting:
  model: hybrid     # hybrid/ets/ar
  horizon: 5        # Шагов прогноза