apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-scaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-scaler
  template:
    metadata:
      labels:
        app: my-scaler
    spec:
      containers:
      - name: my-scaler
        image: my-scaler:latest